---
- hosts: all
  become: true
  pre_tasks:
    - name: Ensure package database is up-to-date
      apt:
        update-cache: yes
      when: ansible_os_family == 'Debian'
    - name: Create users
      user:
        name: "{{ item }}"
        groups: users
        append: true
      with_items:
        - usr1
        - usr2

  vars:
    samba_netbios_name: SAMBA_TEST
    samba_server_string: 'Welcome to the test file server'
    samba_workgroup: TESTGROUP

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never
    samba_users:
      - name: usr1
        password: usr1
      - name: usr2
        password: usr2

    samba_shares_root: /srv/samba
    samba_shares:
      - name: restrictedshare
      - name: privateshare
        comment: 'Only readable/writeable by usr1'
        valid_users: usr1
        write_list: usr1
        group: usr1
      - name: protectedshare
        public: yes
        comment: 'Public, but only writeable by usr2'
        write_list: usr2
        group: users
      - name: publicshare
        comment: 'Public share, writeable by all members of group ‘users’'
        public: yes
        write_list: +users
        group: users
        setype: public_content_t
      - name: guestshare
        comment: 'Share accessible for guests'
        guest_ok: yes
        writable: yes
  roles:
    - role_under_test
